### ISSUE TITLE
Possible issue parsing FASTA?

### ISSUE THREAD

**Issue by wyattmcdonnell** [lpipes/AncestralClust#2]
Hi, thanks for writing AncestralClust! Looks like a very cool tool. Unfortunately, I'm hitting an error with properly formatted FASTA, minimal reproducible example is:

```
./ancestralclust -I test.fasta -d test
```
I've attached `test.fasta` to this issue (just have to change the extension from `.txt` to `.fasta`) as [test.txt](https://github.com/lpipes/AncestralClust/files/5805311/test.txt). Altering the record name of the first record leads to a perpetual `BAD BASE in sequence 2 base 0: >` error, regardless of whether I change the record name of the first record. Thank you for any help you can provide!

**Comment by lpipes** [comment]
Hi, AncestralClust expects the sequence to be all in one line. To convert your file try:
`sed -i ':a; $!N; /^>/!s/\n\([^>]\)/\1/; ta; P; D' test.fasta`

**Comment by wyattmcdonnell** [comment]
Hmm. That produces expected output like this:

```
>GACTAACCAGTTCATG-1
ATGGAGTTTGGGCTGAGCTGGGTTTTCCTTGTTGCTATTATAAAAGGTGTCCAGTGTCAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCAAGCCTGGAGGGTCCCTGACACTCTCCTGTGCAGCCTCTGGATTCACCTACAGTGACTACTATATAAGTTGGATCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGATTTCATACATTAGTTATGGTGGTGGTACCATATACTACGCAGACTCTGTAAAGGGCCGATTCACCCTCTCCAGGGACAACGCCAGGAACTCAGTGTTTCTGCAAATGACCAGCCTGAGAGCCGAGGACACGGCCGTCTACTACTGTGCGAGATACGTGATTTATAACTCAAACGACGTGGCGGGGTACTTGGACCCCTGGGGCCGGGGAACCCTGGTCACCGTCTCCTCAG
>ATCCGAACACCATCCT-1
ATGGAGTTTGGGCTGAGCTGGGTTTTCCTTGTTGCTATTATAAAAGGTGTCCACTGTCAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCAAGCCTGGAGGGTCCCTGACACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTGACTACTACATAACCTGGATCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGATTTCATACATTAGTTTTGGTGGTGGTACCATATACTACGCAGACTCTGTGAAGGGCCGATTCACCCTCTCCAGGGACAACGCCAGGAACTCACTGTTTCTGCAAATGACCAGCCTGAGAGCCGAGGACACGGCCGTCTACTATTGTGCGAGATACGTGATTTATAATTCAAACGACGTGGCGGGGTATTTCGACCCCTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAG
>ACTATCTCAATAGCAA-1
ATGGAGTTTGGGCTGAGCTGGGTTTTCCTTGTTGCTATTATAAAAGGTGTCCAGTGTCAGGTGCAGCTGTTGGAGTCTGGGGGAGGCTTGGTCAAGCCTGGAGGGTCCCTGACACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGGGACTACTACATAACCTGGATCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGATTTCATACATTAGTTTTGGTGGTGGTACCATATACTACGCAGACTCTGTGAAGGGCCGATTCACCCTCTCCAGGGACAACGCCAGGAACTCACTGTTTCTGCAAATGACCAGCCTGAGAGCCGAGGACACGGCCGTCTACTACTGTGCGAGATACGTGATTTATAATTCAAACGACGTGGCGGGCTACTTCGACCCCTGGGGCCGGGGAACCCTGGTCACCGTCTCCTCAG
>AGTTGGTAGTAGCGGT-1
ATGGAGTCTGGGCTGAGCTGGGTTTTCCTAGTTGCTATTATAAAAGGTGTCCAGTGTCAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCAAGCCTGGAGGGTCCCTGACACTCTCCTGTGCAGCCTCTGGATTCACCTACAGTGACTACTATATAAGTTGGATCCGCCAGGCTCCAGGGAAGGGCCTGGAGTGGATTTCATATATTAGTTTTGGTGGTGGTACCATATATTACGCAGGCTCTGTGAAGGGCCGATTCACCCTCTCCAGGGACAACGCCAAGAACTCAGTGTTTCTGCAAATGACCAGCCTGAGAGCCGACGACACGGCCGTCTACTACTGTGCGAGATACGTAATTTATAACTCAAACGACGTGGCGGGGTATTTCGACCCCTGGGGCCGGGGAACCCTGGTCACCGTCTCCTCAG
```
but now triggers a segfault:
```
Number of sequences: 183
Number of clusters: 10
Number of threads: 1
kseq is 50
number_of_clusters is 10
Choosing 50 sequences at random...
Took 0.001812 seconds
Creating distance matrix...
Took 0.696131 seconds
Longest Branch: 0.216074 node: 50
made 9 cuts
Segmentation fault
```

**Comment by lpipes** [comment]
I haven't added a check yet for empty sequences. There is an empty sequence in your file:
>ACCGTAATCTCTAGGA-1
""

**Comment by wyattmcdonnell** [comment]
Hmm, sorry about that. Stripped out empty sequences. Attaching the complete version here, still hitting segfault:
[test_clean.txt](https://github.com/lpipes/AncestralClust/files/5805424/test_clean.txt)

**Comment by lpipes** [comment]
It looks like an optimization error thanks I will work on this. In the mean time, your file works for me if you compile with these flags (also will work if you use `make debug`):
`gcc -g -w -fopenmp -o ancestralclust needleman_wunsch.c alignment.c alignment_scoring.c hashmap.c kalign/run_kalign.c kalign/tlmisc.c kalign/tldevel.c kalign/parameters.c kalign/rwalign.c kalign/alignment_parameters.c kalign/idata.c kalign/aln_task.c kalign/bisectingKmeans.c kalign/esl_stopwatch.c kalign/aln_run.c kalign/alphabet.c kalign/pick_anchor.c kalign/sequence_distance.c kalign/euclidean_dist.c kalign/aln_mem.c kalign/tlrng.c kalign/aln_setup.c kalign/aln_controller.c kalign/weave_alignment.c kalign/aln_seqseq.c kalign/aln_profileprofile.c kalign/aln_seqprofile.c WFA/mm_allocator.c WFA/vector.c WFA/affine_wavefront.c WFA/affine_wavefront_penalties.c WFA/edit_cigar.c WFA/affine_wavefront_reduction.c WFA/affine_wavefront_align.c WFA/affine_wavefront_utils.c WFA/string_padded.c WFA/affine_wavefront_extend.c WFA/affine_wavefront_backtrace.c ancestralclust.c options.c math.c opt.c -lm -pthread -lz`
Also I recommend increasing the value of -k to maybe >100 for your file so that the initial clusters are a sufficient representative of the dataset

**Comment by lpipes** [comment]
These are the clusters I got with the default -n 10 and -k 50 values
[1.txt](https://github.com/lpipes/AncestralClust/files/5806503/1.txt)
[0.txt](https://github.com/lpipes/AncestralClust/files/5806504/0.txt)


[19.txt](https://github.com/lpipes/AncestralClust/files/5806493/19.txt)
[18.txt](https://github.com/lpipes/AncestralClust/files/5806494/18.txt)
[17.txt](https://github.com/lpipes/AncestralClust/files/5806495/17.txt)
[16.txt](https://github.com/lpipes/AncestralClust/files/5806496/16.txt)
[15.txt](https://github.com/lpipes/AncestralClust/files/5806497/15.txt)
[14.txt](https://github.com/lpipes/AncestralClust/files/5806498/14.txt)
[13.txt](https://github.com/lpipes/AncestralClust/files/5806499/13.txt)
[12.txt](https://github.com/lpipes/AncestralClust/files/5806500/12.txt)
[11.txt](https://github.com/lpipes/AncestralClust/files/5806501/11.txt)
[10.txt](https://github.com/lpipes/AncestralClust/files/5806502/10.txt)










[4.txt](https://github.com/lpipes/AncestralClust/files/5806490/4.txt)
[3.txt](https://github.com/lpipes/AncestralClust/files/5806491/3.txt)
[2.txt](https://github.com/lpipes/AncestralClust/files/5806492/2.txt)



[5.txt](https://github.com/lpipes/AncestralClust/files/5806489/5.txt)

[9.txt](https://github.com/lpipes/AncestralClust/files/5806485/9.txt)
[8.txt](https://github.com/lpipes/AncestralClust/files/5806486/8.txt)
[7.txt](https://github.com/lpipes/AncestralClust/files/5806487/7.txt)
[6.txt](https://github.com/lpipes/AncestralClust/files/5806488/6.txt)

**Comment by wyattmcdonnell** [comment]
Interesting. Trying this again with [clust_test.txt](https://github.com/lpipes/AncestralClust/files/5807032/clust_test.txt) and still hitting some errors:

```
(base) wyatt.mcdonnell@bespin1 [~/git/AncestralClust] [23:30] > ./ancestralclust -i clust_test.fasta 
Number of sequences: 6925
Number of clusters: 10
Number of threads: 1
kseq is 50
number_of_clusters is 10
Choosing 50 sequences at random...
Took 0.004819 seconds
Creating distance matrix...
Took 5.813751 seconds
Longest Branch: 0.213101 node: 26
made 9 cuts
number in cluster1: 45
number in cluster2: 4
number in cluster3: 1
number in cluster4: 7
largest cluster is 45
sum of clusters is 57
average is 0.345329
printing initial clusters...
saving clustr format...
new average: 0.345329
number of nodes to cut: 5
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Took 12.920910 seconds
Starting to assign sequences to clusters

BAD BASE in sequence 1 base 0: ?
```
Triple-checked the following:

1. Using `make debug` build
2. No empty records in input
3. No duplicate records

**Comment by lpipes** [comment]
I was able to cluster your sequences using this command:
`ancestralclust -i clust_test.txt -f`
What system are you using?
[9.txt](https://github.com/lpipes/AncestralClust/files/5807144/9.txt)
[8.txt](https://github.com/lpipes/AncestralClust/files/5807145/8.txt)
[7.txt](https://github.com/lpipes/AncestralClust/files/5807146/7.txt)
[6.txt](https://github.com/lpipes/AncestralClust/files/5807147/6.txt)
[5.txt](https://github.com/lpipes/AncestralClust/files/5807148/5.txt)
[4.txt](https://github.com/lpipes/AncestralClust/files/5807149/4.txt)
[3.txt](https://github.com/lpipes/AncestralClust/files/5807150/3.txt)
[2.txt](https://github.com/lpipes/AncestralClust/files/5807151/2.txt)
[17.txt](https://github.com/lpipes/AncestralClust/files/5807152/17.txt)
[16.txt](https://github.com/lpipes/AncestralClust/files/5807153/16.txt)
[15.txt](https://github.com/lpipes/AncestralClust/files/5807154/15.txt)
[14.txt](https://github.com/lpipes/AncestralClust/files/5807155/14.txt)
[13.txt](https://github.com/lpipes/AncestralClust/files/5807156/13.txt)
[12.txt](https://github.com/lpipes/AncestralClust/files/5807157/12.txt)
[11.txt](https://github.com/lpipes/AncestralClust/files/5807158/11.txt)
[10.txt](https://github.com/lpipes/AncestralClust/files/5807159/10.txt)
[1.txt](https://github.com/lpipes/AncestralClust/files/5807160/1.txt)
[0.txt](https://github.com/lpipes/AncestralClust/files/5807161/0.txt)

**Comment by wyattmcdonnell** [comment]
Machine details:
- `uname -r: 5.4.74-36.135.amzn2.x86_64 GNU/Linux` (AWS)

`lscpu` report:
```
lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
Stepping:            4
CPU MHz:             3077.662
BogoMIPS:            4999.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
```
`gcc --version`:
```
gcc --version
clang version 9.0.1 (/mnt/home/adam.azarchs/crosstool/clang/llvm/llvm/tools/clang c1a0a213378a458fbea1a5c77b315c7dce08fd05)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/build/toolchains/versions/2.3.10/bin
```

Any other helpful info I can provide?

**Comment by lpipes** [comment]
I was able to reproduce your error and made the fix. I tested your file again and it worked for me:
`ancestralclust -i clust_test.txt -d test -f`

**Comment by wyattmcdonnell** [comment]
I'm now at `1aa3420 (HEAD -> master, origin/master, origin/HEAD) bug in printRootSeqs`. After `make debug` I see the following:

```
(base) wyatt.mcdonnell@bespin1 [~/git/AncestralClust] [12:44] > ./ancestralclust -i clust_test.fasta -d test -f
Number of sequences: 6925
Number of clusters: 10
Number of threads: 1
kseq is 50
number_of_clusters is 10
Choosing 50 sequences at random...
Took 0.005504 seconds
Creating distance matrix...
Took 5.953564 seconds
Longest Branch: 0.256018 node: 49
made 8 cuts
number in cluster1: 43
number in cluster2: 3
number in cluster3: 4
number in cluster4: 6
largest cluster is 43
sum of clusters is 56
average is 0.340749
printing initial clusters...
Error opening fasta file!(base)
```

**Comment by lpipes** [comment]
I haven't written a check yet to see if the directory you're writing to already exists.

**Comment by wyattmcdonnell** [comment]
Confirmed that this was the issue! Thanks a ton for all of your help @lpipes!
